-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/ontologysync_bundles (
  osb_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  osb_bundle_id VARCHAR(100) NOT NULL,
  osb_label VARCHAR(255) DEFAULT NULL,
  osb_description TEXT DEFAULT NULL,
  osb_repo_commit VARCHAR(40) DEFAULT NULL,
  osb_installed_by INTEGER UNSIGNED DEFAULT NULL,
  osb_installed_at BLOB NOT NULL,
  osb_updated_at BLOB NOT NULL,
  osb_status VARCHAR(20) DEFAULT 'installed' NOT NULL
);

CREATE UNIQUE INDEX osb_bundle_id_unique ON /*_*/ontologysync_bundles (osb_bundle_id);

CREATE INDEX idx_osb_status ON /*_*/ontologysync_bundles (osb_status);


CREATE TABLE /*_*/ontologysync_modules (
  osm_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  osm_module_id VARCHAR(100) NOT NULL,
  osm_bundle_id INTEGER UNSIGNED NOT NULL,
  osm_label VARCHAR(255) DEFAULT NULL,
  osm_installed_at BLOB NOT NULL
);

CREATE UNIQUE INDEX osm_bundle_module_unique ON /*_*/ontologysync_modules (osm_bundle_id, osm_module_id);

CREATE INDEX idx_osm_bundle_id ON /*_*/ontologysync_modules (osm_bundle_id);

CREATE INDEX idx_osm_module_id ON /*_*/ontologysync_modules (osm_module_id);


CREATE TABLE /*_*/ontologysync_pages (
  osp_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  osp_bundle_id INTEGER UNSIGNED NOT NULL,
  osp_module_id INTEGER UNSIGNED NOT NULL,
  osp_page_name VARCHAR(255) NOT NULL,
  osp_page_namespace INTEGER NOT NULL,
  osp_wiki_page_id INTEGER UNSIGNED DEFAULT NULL,
  osp_content_hash VARCHAR(71) DEFAULT NULL,
  osp_source_file VARCHAR(255) DEFAULT NULL,
  osp_installed_at BLOB NOT NULL,
  osp_updated_at BLOB NOT NULL
);

CREATE UNIQUE INDEX osp_page_unique ON /*_*/ontologysync_pages (osp_page_namespace, osp_page_name);

CREATE INDEX idx_osp_bundle_id ON /*_*/ontologysync_pages (osp_bundle_id);

CREATE INDEX idx_osp_module_id ON /*_*/ontologysync_pages (osp_module_id);

CREATE INDEX idx_osp_wiki_page_id ON /*_*/ontologysync_pages (osp_wiki_page_id);
