-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/ontologysync_bundles (
  osb_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
  osb_bundle_id VARCHAR(100) NOT NULL,
  osb_version VARCHAR(50) NOT NULL,
  osb_label VARCHAR(255) DEFAULT NULL,
  osb_description TEXT DEFAULT NULL,
  osb_repo_commit VARCHAR(40) DEFAULT NULL,
  osb_installed_by INT UNSIGNED DEFAULT NULL,
  osb_installed_at BINARY(14) NOT NULL,
  osb_updated_at BINARY(14) NOT NULL,
  osb_status VARCHAR(20) DEFAULT 'installed' NOT NULL,
  UNIQUE INDEX osb_bundle_id_unique (osb_bundle_id),
  INDEX idx_osb_status (osb_status),
  PRIMARY KEY(osb_id)
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/ontologysync_modules (
  osm_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
  osm_module_id VARCHAR(100) NOT NULL,
  osm_version VARCHAR(50) NOT NULL,
  osm_bundle_id INT UNSIGNED NOT NULL,
  osm_label VARCHAR(255) DEFAULT NULL,
  osm_installed_at BINARY(14) NOT NULL,
  UNIQUE INDEX osm_bundle_module_unique (osm_bundle_id, osm_module_id),
  INDEX idx_osm_bundle_id (osm_bundle_id),
  INDEX idx_osm_module_id (osm_module_id),
  PRIMARY KEY(osm_id)
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/ontologysync_pages (
  osp_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
  osp_bundle_id INT UNSIGNED NOT NULL,
  osp_module_id INT UNSIGNED NOT NULL,
  osp_page_name VARCHAR(255) NOT NULL,
  osp_page_namespace INT NOT NULL,
  osp_wiki_page_id INT UNSIGNED DEFAULT NULL,
  osp_content_hash VARCHAR(71) DEFAULT NULL,
  osp_source_file VARCHAR(255) DEFAULT NULL,
  osp_installed_version VARCHAR(50) DEFAULT NULL,
  osp_installed_at BINARY(14) NOT NULL,
  osp_updated_at BINARY(14) NOT NULL,
  UNIQUE INDEX osp_page_unique (osp_page_namespace, osp_page_name),
  INDEX idx_osp_bundle_id (osp_bundle_id),
  INDEX idx_osp_module_id (osp_module_id),
  INDEX idx_osp_wiki_page_id (osp_wiki_page_id),
  PRIMARY KEY(osp_id)
) /*$wgDBTableOptions*/;
